/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TesterAgent } from "./TesterAgent";
import { TesterAgentCountArgs } from "./TesterAgentCountArgs";
import { TesterAgentFindManyArgs } from "./TesterAgentFindManyArgs";
import { TesterAgentFindUniqueArgs } from "./TesterAgentFindUniqueArgs";
import { DeleteTesterAgentArgs } from "./DeleteTesterAgentArgs";
import { TesterAgentService } from "../testerAgent.service";
@graphql.Resolver(() => TesterAgent)
export class TesterAgentResolverBase {
  constructor(protected readonly service: TesterAgentService) {}

  async _testerAgentsMeta(
    @graphql.Args() args: TesterAgentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TesterAgent])
  async testerAgents(
    @graphql.Args() args: TesterAgentFindManyArgs
  ): Promise<TesterAgent[]> {
    return this.service.testerAgents(args);
  }

  @graphql.Query(() => TesterAgent, { nullable: true })
  async testerAgent(
    @graphql.Args() args: TesterAgentFindUniqueArgs
  ): Promise<TesterAgent | null> {
    const result = await this.service.testerAgent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TesterAgent)
  async deleteTesterAgent(
    @graphql.Args() args: DeleteTesterAgentArgs
  ): Promise<TesterAgent | null> {
    try {
      return await this.service.deleteTesterAgent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
