/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ProductOwnerAgent as PrismaProductOwnerAgent,
} from "@prisma/client";

export class ProductOwnerAgentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProductOwnerAgentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.productOwnerAgent.count(args);
  }

  async productOwnerAgents(
    args: Prisma.ProductOwnerAgentFindManyArgs
  ): Promise<PrismaProductOwnerAgent[]> {
    return this.prisma.productOwnerAgent.findMany(args);
  }
  async productOwnerAgent(
    args: Prisma.ProductOwnerAgentFindUniqueArgs
  ): Promise<PrismaProductOwnerAgent | null> {
    return this.prisma.productOwnerAgent.findUnique(args);
  }
  async createProductOwnerAgent(
    args: Prisma.ProductOwnerAgentCreateArgs
  ): Promise<PrismaProductOwnerAgent> {
    return this.prisma.productOwnerAgent.create(args);
  }
  async updateProductOwnerAgent(
    args: Prisma.ProductOwnerAgentUpdateArgs
  ): Promise<PrismaProductOwnerAgent> {
    return this.prisma.productOwnerAgent.update(args);
  }
  async deleteProductOwnerAgent(
    args: Prisma.ProductOwnerAgentDeleteArgs
  ): Promise<PrismaProductOwnerAgent> {
    return this.prisma.productOwnerAgent.delete(args);
  }
}
