/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeveloperAgent } from "./DeveloperAgent";
import { DeveloperAgentCountArgs } from "./DeveloperAgentCountArgs";
import { DeveloperAgentFindManyArgs } from "./DeveloperAgentFindManyArgs";
import { DeveloperAgentFindUniqueArgs } from "./DeveloperAgentFindUniqueArgs";
import { DeleteDeveloperAgentArgs } from "./DeleteDeveloperAgentArgs";
import { DeveloperAgentService } from "../developerAgent.service";
@graphql.Resolver(() => DeveloperAgent)
export class DeveloperAgentResolverBase {
  constructor(protected readonly service: DeveloperAgentService) {}

  async _developerAgentsMeta(
    @graphql.Args() args: DeveloperAgentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DeveloperAgent])
  async developerAgents(
    @graphql.Args() args: DeveloperAgentFindManyArgs
  ): Promise<DeveloperAgent[]> {
    return this.service.developerAgents(args);
  }

  @graphql.Query(() => DeveloperAgent, { nullable: true })
  async developerAgent(
    @graphql.Args() args: DeveloperAgentFindUniqueArgs
  ): Promise<DeveloperAgent | null> {
    const result = await this.service.developerAgent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DeveloperAgent)
  async deleteDeveloperAgent(
    @graphql.Args() args: DeleteDeveloperAgentArgs
  ): Promise<DeveloperAgent | null> {
    try {
      return await this.service.deleteDeveloperAgent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
